language: node_js
node_js:
- "stable"
install:
  - npm install
script:
  - npm test
services:
- postgresql
env:
- NODE_ENV=test DB_USERNAME=enjames DB_PASSWORD=password DB_NAME=ridemywaytest
before_script:
- psql -c 'create database ridemywaytest;' -U postgres
- psql -c "CREATE USER enjames WITH PASSWORD 'password';" -U postgres
cache:
  directories:
    - "node_modules"
after_success :
    - npm run coverage
